name: userapp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  mapbox_gl: ^0.8.0
  flutter:
    sdk: flutter
  flutter_feather_icons: ^1.0.3
  flutter_svg: ^0.19.0
  cupertino_icons: ^1.0.0
  rxdart: ^0.24.1
  graphql_flutter: ^3.1.0
  json_serializable: ^3.5.0
  geolocator: ^6.0.0
dev_dependencies:
  flutter_launcher_icons: "^0.8.0"
  build_runner: ^1.10.3
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/download.png"
flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/icons/